### ISSUE TITLE
minterf files not generated

### ISSUE THREAD

**Issue by lmanubens** [MarcelBeining/T2N#2]
Hi Marcel,

Your work is very nice and interesting! 
I'm looking forward to being able to use it.

I have been playing with the tutorial and I'm not able to get running the most basic steps. When running the first simulation (line 95 in t2n_Tutorial.m) I get the following error:

> Error using load
Unable to read file '/home/linus/Desktop/ap_sim/morphos/hocs/cell_Tree_1_minterf.dat'. No such file or directory.

> Error in t2n (line 325)
        origminterf{t} = load(fullfile(modelFolder,'morphos','hocs',sprintf('%s_minterf.dat',tree{t}.NID)));

I have investigated a bit and it seems that %s_minterf.dat and '%s_minterf.mat should be generated in the function t2n_writeTrees.m. However, the code seems to rely on copying them from a server without public access (or I did not find how to connect to it in the documentation).

In the help of the function t2n_makeNseg.m you specify that minterf is created by neuron_template_tree. But I could not see where in the template generation the minterf files could be created. I'm using the neuron_template_tree function found in the TREESinterim toolbox found here: http://www.treestoolbox.org/download.html 
I wonder whether a different version of this function should be used. 

With best regards,
Linus Manubens Gil

**Comment by MarcelBeining** [comment]
Hi Linus,
thank you very much for your interest in T2N and for reporting that issue to us!
You are on the right track!
Actually the Treestoolbox-interim version does not have the correct version of the neuron_template_tree.m file (it has not yet included the creation of the mintef files). This is our fault as it looks on the website as this should be the version-to-use! We will change this now.
In the meantime, please simply download and install the treestoolbox github-master-branch, which is the newest version of Treestoolbox and has the correct file:
https://github.com/cuntzlab/treestoolbox/archive/master.zip

**Comment by MarcelBeining** [comment]
We now changed the treestoolbox content accordingly to avoid further confusion:
http://www.treestoolbox.org/download.html

**Comment by lmanubens** [comment]
Thanks a lot for the fast feedback!
After using that version the test runs smoothly with the sample_tree. 
However, when testing with few other swcs I get some errors, I'll open a new issue to allow you to replicate the error I get.
