### ISSUE TITLE
t2n can't find mknrndll

### ISSUE THREAD

**Issue by neuroptics** [MarcelBeining/T2N#5]
Hi Marcel,

Just a novice here without much NEURON or TREES experience, playing around with your tutorial. Very cool! I am having a few issues. First, t2n fails to compile the example .mod file you provide (vecevent.mod), because it can't find mknrndll. This is a new system (win 10) so I installed a fresh copy of NEURON (v7.6.7.) and MATLAB R2018b, looks like the path specified on line 444 of t2n is incorrect. I was able to run mkrnrdll manually and that brings me to issue #6 , an error in NEURON itself.

Also, I have the latest available version of T2N.

Thanks,
David Klorig

**Comment by MarcelBeining** [comment]
Hi @neuroptics ,
thanks for reporting.
Seems some folder structure and library versions changed from NEURON 7.4 to NEURON 7.6.7.
I am on it.
As a workaround until then you might want to install NEURON 7.4, maybe your other issue #6 is gone, too (if so, please report).

**Comment by neuroptics** [comment]
Hi Marcel,

Yes, both issues (this and #6 ) are solved by installing NEURON 7.4. 

Thanks!
David
