### ISSUE TITLE
git clone authentication problems

### ISSUE THREAD

**Issue by LauraDovek** [MarcelBeining/T2N#8]
@neuroptics Sounds like you did not download T2N using a git software but simply by downloading the zip or so, right? Clone the repo using git, will make a lot of things easier including getting the newest updates :-)

Hi Marcel, 
 I am unfortunately having the exact same issues as neuroptics! I am using a mac and I am trying to clone the repro but it tells me that my authentication failed and that I "may not have permission to access the repository or the repository may have been archived" 
Kind Regards, 
Laura

_Originally posted by @MarcelBeining in https://github.com/MarcelBeining/T2N/issues/4#issuecomment-496564348_

**Comment by MarcelBeining** [comment]
Dear @LauraDovek ,
you are using 
`git clone git@github.com:MarcelBeining/T2N.git`
as clone command?
If yes, have you already set up your ssh keys? (see [here ](https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account)for help)
